### ISSUE TITLE
Base64 checking logic is wrong

### ISSUE THREAD

**Issue by Jooho** [opdev/pachyderm-operator#4]
In order to check base64 encoding for the CR parameters, operator uses `base64.StdEncoding.DecodeString(value)`. This is working properly but the err check should !=.

~~~
func toBytes(value string) []byte {
	fmt.Println(value)
	if aimlv1beta1.IsBase64Encoded(value) {
		if out, err := base64.StdEncoding.DecodeString(value); err == nil {
			return out
		}
	}
	return []byte(value)
}
~~~
With above condition, it can check "true" value.

**Comment by OchiengEd** [comment]
Sounds good. I have refactored this in a local branch and should be available soon.
